config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get '/signin' => 'sessions#signin', as: 'signin_session'
  post '/signin' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout_session'

  resources :users, only: [:show,:new, :create]
  resources :addresses

  resources :items
  resources :categories  

  get 'stock_report/', to: "categories#stock_report"
  get '/ticket/:address_id', to: "items#ticket", :as => 'ticket'

  post '/add_item/:item_id' => 'items#add_item', :as => 'add_item'
  delete 'item/:id' => "items#destroy"

  get '/auth/facebook/callback', to: 'sessions#create'

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
    # validates :user,  presence: true
    # validates :title, :receiver, :street, :country, :state,
    #         :city, :postal_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    # has_many :line_items, dependent: :destroy
    # has_many :items # through: :line_items##

    # belongs_to :user

#     def add_item(item)
#       # item = items.where('item_id = ?', item_id).first
#       # if item
#       #   # increase the quantity of product in cart
#       #   item.quantity=item.quantity + 1
#       #   save
#       # else
#       # #    # product does not exist in cart
#       #   item = Item.find(item_id)
#       puts item.inspect
#         self.items <<  item
#     end
# #       save
# # end


end

app/models/categorization.rb
class Categorization < ApplicationRecord
    belongs_to :category
    belongs_to :item
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categorizations
    has_many :items, :through => :categorizations

    validates_uniqueness_of :category_name, :case_sensitive => false, message: 'has already taken'
    validates_format_of :category_name, :with => /[a-zA-Z]/, message: 'There should be at least one character.'
    validates :category_name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
    # before_destroy :not_referenced_any_line_item
    default_scope { order('created_at DESC') }

    validates_uniqueness_of :isbn
    validates :item_name, :unit_price, :quantity, presence: true
    validates :unit_price, :quantity, numericality: { only_integer: true }, length: { maximum: 7}
    # validates :chosen_quantity

    validates :desc, length: {maximum: 1000, too_long: "%{count} character is the maximum allowed"}
    validates :item_name, length: {maximum: 140, too_long: "%{count} character is the maximum allowed"}
   
    validates_length_of :isbn, :minimum => 12
    validates_uniqueness_of :isbn
    
    has_many :categorizations
    has_many :categories, :through => :categorizations
    # has_many :line_items
    # belongs_to :cart
    belongs_to :user, optional: true

    has_one_attached :photo
    # mount_uploader :image, ImageUploader
    # serialize :image, JSON #for Sqlite only

    BRAND = %w{ Samson BB Quallity }
    FINISH = %w{ NOUKOD BB Quallity }
    CONDTION = %w{ BALLY BB Quallity }


    def photo?
      errors.add(:base, 'Please upload an image for yout product!') unless photo.attached?
    end

  
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  # belongs_to :item
  # belongs_to :cart
  # belongs_to :order ###

  # def total_price ##
  #   self.quantity * self.item.unit_price
  # end
  
end

app/models/order.rb
class Order < ApplicationRecord
    # belongs_to :client
    # has_many :orderdetails
    # has_many :line_items, dependent: :destroy ###

end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord


    # belongs_to :order
    # belongs_to :item
      
    # validates :order_id, client_id, :item_id, :quantity, :unit_price, presence: true
      
    # scope :by_week, lambda{ where('created_at > ?', Time.now-7.days)  }
    # scope :by_day, lambda{ where('created_at > ?', Time.now-1.days)  }
      
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :fullname, :email, :password, presence: true
    validates :email, uniqueness: true, :case_sensitive => false #, message: 'has already taken, choice not avaible!'
  
    has_many :items
    # has_one :cart
    # has_many :categories 


    # validates_uniqueness_of :category_name, :case_sensitive => false, message: 'has already taken'
    # validates_format_of :category_name, :with => /[a-zA-Z]/, message: 'There should be at least one character.'
    # validates :category_name, presence: true
  
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :logged_in?, only: [:index, :new, :create]
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = Address.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id

    if @address.save
       redirect_to ticket_path(@address)
      # render :new 
    end
    
  end

  def update
    if @address.update(address_params)
     redirect_to addresses_path 
     
    else
       render :edit 
    end
 
  end
  
  
  def destroy
    @address.destroy
    redirect_to addresses_url
  end
 
   
    
  private
    def address_params
      params.require(:address).permit(:receiver, :company, :street,
                                      :street_extra, :city, :postal_code,
                                      :state, :country, :phone)
    end

    def set_address
      @address = Address.find_by(id: params[:id])
      # @address.user_id
   end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        User.find_by(id: session[:user_id]) if session[:user_id]
    end

   def logged_in?
    !!current_user
  end

   def require_logged_in
      redirect_to root_path unless logged_in?
    end

    def current_cart 
      Cart.find_by(user_id:current_user.id)
    end

    def get_total_price(cart)
      # cart.map{|x| x[:unit_price]}.reduce(:+)
      puts "----------------"
      puts cart.inspect 
      puts "----------------"
      total=0
      cart.each do |item|
        if item.any?
          total+=item["unit_price"] * item["chosen_quantity"]
        end
      end
      total
    end
    

end

app/helpers/carts_helper.rb
module CartsHelper
 
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

    def author_own(item)
        logged_in? && current_user.admin
    end
   
        
    def empty(cart)
        if session[:cart]
            session[:cart].clear
        end
    end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb


<div class="form-group">
  <div class="col-md-6 col-md-offset-3">
   
    <%= form_for(@address) do |f| %>
        <div class="field">
        <%= f.label :receiver, "Receiver's Name " %><br>
        <%= f.text_field :receiver, placeholder: "Receiver", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :company %><br>
        <%= f.text_field :company, placeholder: "Company", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street, placeholder: "1st Street", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :street_extra, 'Suite / Apartment' %><br>
        <%= f.text_field :street_extra, placeholder: "2nd Street (optional)", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city, placeholder: "city", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :postal_code, "Zip / Postcode" %><br>
        <%= f.text_field :postal_code, maxlength: 10, placeholder: "Zip/Postal Code", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state, placeholder: "State", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :country %><br>
        <%= f.text_field :country, placeholder: "Country", class: "form-control"  %>
        </div>
        <div class="field">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, placeholder: "Phone", class: "form-control"  %>
        </div>
        <div class="actions">
         <%= f.submit "Create Address", class: "btn btn-primary" %>
        </div>

    <% end %>
  </div>
</div


app/views/addresses/edit.html.erb
<br><br>

<%= render 'form', title: 'Edit Address' %>

app/views/addresses/index.html.erb


<h2>All Addresses</h2>
<div class='user-account__left'>
  <h1>Addresses</h1>
  <%= link_to 'New Address', new_address_path %>
</div>
<div class='user-account__right'>
  <h3>Address Book</h3>
  <% @addresses.each do |address| %>
    <div class='address-item'>
      <%= address.country %>
      <%= address.phone %>
      <%= address.city %>
      <%= address.receiver %>
      <%= address.company %>
      <div class='actions'>
        <%= link_to 'Edit', edit_address_path(address) %> | <%= link_to 'Delete', address, method: :delete %>
      </div>
    </div>
  <% end %>
</div>

app/views/addresses/new.html.erb
<br><br><br><br>

<%= render 'form', title: 'New Address' %>
<%= link_to "Back to All Items", categories_path, class: "btn btn-primary btn-light" %>

app/views/addresses/show.html.erb
</br><br>
<h2>Your Address</h2>


<p><strong><%= @address.street %>, <%= street_extra %>, <%= @address.city %>, <%= @address.postal_code %> , <%= @address.state %> , <%= @address.country %> .</p>

<h6><strong>Receiver:<%= @address.receiver%></h6>

<h6><strong>Phone:<%= @address.phone%></h6>
