config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get '/signin' => 'sessions#signin', as: 'signin_session'
  post '/signin' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout_session'

  resources :users, only: [:show,:new, :create]
  resources :addresses

  resources :items
  resources :categories  

  get 'stock_report/', to: "categories#stock_report"
  get '/ticket/:address_id', to: "items#ticket", :as => 'ticket'

  post '/add_item/:item_id' => 'items#add_item', :as => 'add_item'
  delete 'item/:id' => "items#destroy"

  get '/auth/facebook/callback', to: 'sessions#create'

end

app/models/item.rb
class Item < ApplicationRecord
    # before_destroy :not_referenced_any_line_item
    default_scope { order('created_at DESC') }

    validates_uniqueness_of :isbn
    validates :item_name, :unit_price, :quantity, presence: true
    validates :unit_price, :quantity, numericality: { only_integer: true }, length: { maximum: 7}
    # validates :chosen_quantity

    validates :desc, length: {maximum: 1000, too_long: "%{count} character is the maximum allowed"}
    validates :item_name, length: {maximum: 140, too_long: "%{count} character is the maximum allowed"}
   
    validates_length_of :isbn, :minimum => 12
    validates_uniqueness_of :isbn
    
    has_many :categorizations
    has_many :categories, :through => :categorizations
    # has_many :line_items
    # belongs_to :cart
    belongs_to :user, optional: true

    has_one_attached :photo
    # mount_uploader :image, ImageUploader
    # serialize :image, JSON #for Sqlite only

    BRAND = %w{ Samson BB Quallity }
    FINISH = %w{ NOUKOD BB Quallity }
    CONDTION = %w{ BALLY BB Quallity }


    def photo?
      errors.add(:base, 'Please upload an image for yout product!') unless photo.attached?
    end

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :require_logged_in
 
    before_action :set_item, only: [:show, :edit, :update, :destroy]



    def index
        @category = Category.find_by(id: params[:id])
        # @items = Item.find_by(id: @category_id).items
        @items = Item.all 

        # respond_to do |format|
        #     format.html { render :index}
        #     format.json {renderj json: @items}
        # end
    end
    
    def ticket
        @address = Address.find_by(id: params[:address_id])
    end
    
    def show
        @user= User.find_by(id: session[:id])
        @category = Category.find_by(id: params[:id])
        # @item = Item.find_by(id: params[:id])
        
        @address = Address.find_by(id: params[:id])
        @category = Category.new

        respond_to do |format|
          format.html { render :show }
          format.json {render json: @item } 
        end
    end

    def new
        @user = User.find_by(id: session[:user_id])
        @item = Item.new
    end
    
    def edit
    end

    def create
       
        # --- 1st way-----
        # user = session[:user_id]
        # @item = Item.new(item_params)
        # @item.user = current_user
        puts params.inspect
        # --- 2nd way-----
        @item = current_user.items.build(item_params)
        # photoname= params[:item][:photo].filename
        # photofile= params[:item][:photo][:tempfile]

        # File.open("./public/#{photoname}","wb") do |f|
        #     f.write(photofile.read)
        # end
        
        @category = Category.find_by(id: params[:item][:category_id])

        respond_to do |format|
            if @item.save
                format.html { redirect_to item_path(@item), notice: 'Item was successfully created.'}
                format.json { render :show, status: :created, location: @item}
            else
                format.html { redirect_to new_item_path }
                format.json { render json: @item.errors, status: :unprocessable_entity }
            end
        end
    end

    def add_item
        item = Item.find_by(id: params[:item_id])
        current_user
        if session[:cart]
          @cart = session[:cart]
        else
          session[:cart] = []
          @cart = session[:cart]
        end

        @cart.push(item) if Item.exists?(item.id)
        redirect_to items_path
    end

 

   
    def update
        @item = Item.find_by(id: params[:id])
        if @item.update(item_params)
              redirect_to @item
        else
              render 'edit'
        end
    end
    
   


    def remove_item_from(cart)
        @cart.delete_at(item)
      end

    def destroy
        @item = Item.find_by(id: params[:id])
        @item.destroy
        redirect_to stock_report_path
    end

    private
       def set_item
           @item = Item.find_by(id: params[:id])
       end
       
       def item_params
         params.require(:item).permit(:item_name, :unit_price, :tax, 
                                      :quantity, :photo, :isbn, :desc, 
                                      :chosen_quantity, category_ids:[])
       end
end

app/helpers/items_helper.rb
module ItemsHelper

    def author_own(item)
        logged_in? && current_user.admin
    end
   
        
    def empty(cart)
        if session[:cart]
            session[:cart].clear
        end
    end


end

app/views/items/_chosen_quantity.html.erb
<div class="form-group">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@item) do |f| %>
            <%= f.select :chosen_quantity, ((0..50).map {|i| [i,i] } << ["No limit",nil]) %>

        <%= f.submit "Add Quantity", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/items/_form.html.erb
<div class="form-group">
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item) do |f| %>
        <%= f.label :category_name, "Choose Or Create A Category:" %><br>
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :category_name do |c| %>
            <% c.label(class: "checkbox-inline input_checkbox") {c.check_box(class: "checkbox") + c.text} %>
        <%end%> 
        <%= link_to "Add a Category", new_category_path, class: "btn btn-primary btn-light" %>
        <br><br>

        <%= f.label :item_name %> <br>
        <%= f.text_field :item_name, placeholder: "Item Name", class: "form-control" %><br>

        <%= f.label :unit_price %><br>
        <%= f.text_field :unit_price, placeholder: "Unit Price", class: "form-control" %><br>


        <%= f.label :tax %><br>
        <%= f.text_field :tax, placeholder: "Tax", class: "form-control" %><br>

        <%= f.label :quantity %><br>
        <%= f.number_field :quantity, placeholder: "Quantity", class: "form-control" %><br>

        <%= f.label :isbn %><br>
        <%= f.text_field :isbn, placeholder: "ISBN", class: "form-control" %><br>

        <%= f.label :Description %><br>
        <%= f.text_area :desc, placeholder: "Description", class: "form-control" %><br>

        <%= f.label :photo %><br>
        <%= f.file_field :photo, class: "form-control" %><br>

        <%= f.submit "Add Item", class: "btn btn-primary" %>
    <% end %>
    </div>
</div>

app/views/items/edit.html.erb

<br><br><br>
<h1>Edit Item Data</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<br><br><br>
<div class="container">
    <div class="bg-text-report">
    <!--<div class="row">-->

        <h2><strong>Your Cart</strong></h2>

        <% if !session[:cart].nil? && !current_user.admin %>
            <table class="table table-dark">
                <thead>
                <tr>
                    <th scope="col">Quantity</th>
                    <th scope="col">Product</th>
                    <th scope="col">Sub Total</th>                 
                    <th scope="col">Total</th>
                </tr>
                </thead>
                <tbody>
                    <% session[:cart].each do |item| %>
                    <tr>
                    <td> <strong><%= item["chosen_quantity"]%> </strong></td>
                    <td> <strong><%= item['item_name']%></strong></td>
                    <td> <strong><%= number_to_currency(item['unit_price']) %></strong></td>
                    <% end %>  
                    <td><strong><%= number_to_currency(get_total_price(session[:cart])) %></strong> </td>
                    </tr>
                </tbody>
            </table>

            <p><%= link_to 'Select More items!', categories_path, class: "btn btn-primary btn-light"%></p>
            <%= link_to "Add Your Address", new_address_path, class: "btn btn-primary btn-light" %>
        <% else %>
            <p><strong>You Do Not Have Any Rights To Purchase. You Must first Login / Register As A Customer!</strong></p>
            <%= link_to "Back to All Items", categories_path, class: "btn btn-primary btn-light" %>
        <% end %>
    </div>
</div>

app/views/items/new.html.erb
<br><br><br>

<h1>Create New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
 <br> <br> <br>
 
<h3 id="item">Current Item</h3><br>

<div class='placeholders' id='item-data'></div>

app/views/items/ticket.html.erb
 <br><br><br>

<div class="container">
    
    <div class="row">
    <h1><strong>Thank You For Buying!</strong></h1>
        <div class="bg-text-tiket">
        <div class="title"><h2><strong>Your ticket!</strong></h2></div>
        <% if !session[:cart].nil? && !current_user.admin %>
         <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col">Quantity</th>
                <th scope="col">Product</th>
                <th scope="col">Sub Total</th>                 
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
            <% session[:cart].each_with_index do |item| %>
              <tr>
                <td> <strong><%= item["chosen_quantity"]%> </strong></td>
                <td> <strong><%= item['item_name']%></strong></td>
                <td> <strong><%= number_to_currency(item['unit_price']) %></strong></td>
            <% end %>  
                <td><strong><%= number_to_currency(get_total_price(session[:cart])) %></strong> </td>
              </tr>   
            </tbody>
         </table>
        <% end %>
        </div>
    </div>
   
    <p>
      <strong>
        Your Order will be sent soon at: 
        <%= @address.street %>, 
        <%= @address.city %>,
        <%= @address.postal_code %>, 
        <%= @address.state %>, 
        <% @address.country %>. 
      <strong>
    </p>

    <p><strong>Receiver: <%= @address.receiver%></strong> </p>
    <p><strong>Phone: <%= @address.phone%></strong> </p>
     <% empty(session[:cart]) %>

</div>

  