config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get '/signin' => 'sessions#signin', as: 'signin_session'
  post '/signin' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout_session'

  resources :users, only: [:show,:new, :create]
  resources :addresses

  resources :items
  resources :categories  

  get 'stock_report/', to: "categories#stock_report"
  get '/ticket/:address_id', to: "items#ticket", :as => 'ticket'

  post '/add_item/:item_id' => 'items#add_item', :as => 'add_item'
  delete 'item/:id' => "items#destroy"

  get '/auth/facebook/callback', to: 'sessions#create'

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categorizations
    has_many :items, :through => :categorizations

    validates_uniqueness_of :category_name, :case_sensitive => false, message: 'has already taken'
    validates_format_of :category_name, :with => /[a-zA-Z]/, message: 'There should be at least one character.'
    validates :category_name, presence: true
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
     before_action :set_category, only: [:show, :edit, :update, :destroy]
    
    def index
        @user_id = session[:id]
        @categories = Category.all
        @items = Item.all 
        
        respond_to do |format|
            format.html {render :index }
            format.json {render json: @categories }
        end
    end

    def show
        @item = Item.new
        
        respond_to do |format|
            format.html {render :show }
            format.json {render json: @category } 
          end
    end

    def new
       
        puts @user.inspect
        @category = Category.new
        @user_id = session[:user_id]
    end

    def stock_report
        @category = Category.all
        @items = Item.all 
    end


    # def edit
    #     @category = Category.find_by(id: params[:id])
    # end
    
    def create
        @category = Category.new(category_params)
      
        if @category.save # && @category.id = @user.id
            redirect_to @category 
            # 'Category was successfully created.' 
        else
            render 'new'
        end
    end

   
    def update
        @category = Category.find_by(id: params[:id])
        if @category.update(category_params)
              redirect_to @category
            #   'Category was successfully updated.' 
        else
              render 'edit'
        end
    end

    def destroy
        @category = Category.find_by(id: params[:id])
        @category.destroy
        redirect_to categories_path
        # 'Category was successfully destroyed.'
    end

    private

      def set_category
        @category = Category.find_by(id: params[:id])
      
      end
    
    def category_params
      params.require(:category).permit(:category_name)
    end
    
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<div class="form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>
      <%= f.label :category_name %></br>
      <%= f.text_field :category_name, required: true, autofocus: true, placeholder: "Category Nname", class: "form-control" %></br>
      
      <%= f.submit "Create Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'View All Categories!', categories_path %></br>

app/views/categories/edit.html.erb
<h1> Edit Category!</h1>
<%= render 'form' %>

<%= link_to "Log Out", logout_session_path, method: :delete, class: "navbar-brand" %>

app/views/categories/index.html.erb
</br></br></br>

<div class="container">
   <button id="all-items">Load Items</button>
   <div class='placeholders' id='categories-data'></div>
   <div class='placeholders' id='items-data'></div>

  <div class='placeholders' id='item-data'></div>
   <div class='placeholders' id='item'></div>


   <div button='one-item'> sigle item </button>
   <div class='placeholders' id=''></div>
</div>
      

app/views/categories/new.html.erb
<h2> Add a Category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<br><br><br>
<h1> Category Name: <%= @category.category_name %></h2>

<%= link_to 'View Full Detail of item', item_path(@category, @item) %>

app/views/categories/stock_report.html.erb
</br></br></br>


<div class="container">
 <div class="title"><h3><strong> Stock Report </strong></h3></div>
   <div class="bg-text-report">
      <div class="row">

      <% if @category.any? && current_user.admin %>
         <% @category.each do |category|%>
            <h3><strong><%= category.category_name %></strong></h3>
               <% category.items.each do |item| %>
                <table class="table table-dark">
                    <thead>
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Remaining</th>
                        <th scope="col">Edit | Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                   
                    <td> <strong><%= item.item_name %></strong></td>
                    <td> <strong><%= number_to_currency(item.unit_price) %></strong></td>
                    <td> <strong><%= item.quantity %></strong></td>
                    <td> <strong><%= item.quantity - item.chosen_quantity %></strong></td>
                
                    <% if author_own(item) && current_user == item.user %> 
                       <td> <%= link_to "Edit", edit_item_path(item) %> | <%= link_to "Delete", item_path(item), method: :delete, data: { confirm: 'Are You Sure?'} %> </td>
                     <% end %>
                    </tr>
                </tbody>
                </table>
                 <% end %>
         <% end %>
                
      <% elsif !@categories.any? && current_user.admin %>
            <p><strong>No Item has Been Yet registered! </strong></p>
            <h4><strong> <%= link_to 'Add New Items', new_item_path %></h4>
      <% end %>
      </div>
   </div>

    <% if current_user.admin %>
         <div class="back-to-preorder-oder"><h4><strong> <%= link_to 'Add New Items', new_item_path, class: "btn btn-primary btn-light"%></h4></div>
      <% end %>
</div>